repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: check-toml

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.3.2
          - "prettier-plugin-toml"

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.16.0
    hooks:
      - id: check-github-workflows
      - id: check-readthedocs
